import type { NextPage } from 'next';
import Head from 'next/head';

const VoteCard = ({ children }) => {
  return (
    <div>
      <div className="flex justify-center items-center uppercase bg-white text-black rounded-md h-52 w-52">
        {children}
      </div>
      <button className="mt-5 bg-red-400 uppercase rounded-md px-4 py-1 w-full">
        Vote for {children}
      </button>
    </div>
  );
};

const Home: NextPage = () => {
  return (
    <div className="bg-gradient-to-t from-darkGrey to-lightGrey text-white h-screen py-16">
      <Head>
        <title>Voting Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-3xl w-full mx-auto">
        <h1 className="text-5xl uppercase font-black text-center">Pick your favourite.</h1>
        <section className="flex justify-between flex-wrap mt-20">
          <VoteCard>Apple</VoteCard>
          <VoteCard>Ball</VoteCard>
          <VoteCard>Cat</VoteCard>
        </section>
      </main>
    </div>
  );
};

export default Home;
