import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import useVotingDapp from '../store/contract.store';
import useEthers from '../store/ethers.srote';

const VoteCard = ({ children }) => {
  return (
    <div>
      <div className="mt-5 flex justify-center items-center uppercase bg-white text-black rounded-md h-52 w-52">
        {children}
      </div>
      <button className="mt-5 bg-red-400 uppercase rounded-md px-4 py-1 w-full">
        Vote for {children}
      </button>
    </div>
  );
};

const Home: NextPage = () => {
  const [candidateName, setCandidateName] = React.useState<string>('John Doe');
  const [candidateAge, setCandidateAge] = React.useState<string>('0');
  const { requestAccounts, accounts, checkMMConnection } = useEthers();
  const {
    getInitialData,
    totalVotes,
    totalCandidates,
    winner,
    manager,
    electionStarted,
    getCandidates,
  } = useVotingDapp();

  const handleConnectWallet = () => {
    void requestAccounts();
  };
  React.useEffect(() => {
    void checkMMConnection();
    void getInitialData();
  }, []);

  console.log(totalVotes, totalCandidates, winner, manager, electionStarted);

  React.useEffect(() => {
    if (totalCandidates > 0) {
      let i = 0;
      for (i = 0; i <= totalCandidates; i++) {
        getCandidates(i);
      }
    }
  }, []);
  return (
    <div className="bg-gradient-to-t from-darkGrey to-lightGrey text-white py-16">
      <Head>
        <title>Voting Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-7xl w-full grid grid-cols-2 mx-auto">
        <div className="flex flex-col px-10">
          <h1 className="text-5xl uppercase font-black text-center">Add Candidate</h1>
          <div className="flex mt-5 items-center justify-between w-full">
            <label className="w-1/4">Candidate Name:</label>
            <input
              value={candidateName}
              onChange={(e) => setCandidateName(e.target.value)}
              className="w-96 text-black h-14 p-4 rounded-lg"
            />
          </div>
          <div className="flex mt-5 items-center justify-between w-full">
            <label>Candidate Age:</label>
            <input
              value={candidateAge}
              onChange={(e) => setCandidateAge(e.target.value)}
              type="number"
              className="w-96 text-black h-14 p-4 rounded-lg"
            />
          </div>
          <button className="p-2 bg-pink-600 rounded-lg mt-5 w-32">Add Candidate</button>
        </div>
        <div>
          <div className="flex items-center">
            <button onClick={handleConnectWallet} className="bg-pink-600 p-2 rounded-lg">
              Connect Wallet
            </button>
            <p className={`p-2 rounded-lg bg-gray-400`}>{accounts[0]}</p>
          </div>
          <h1 className="text-5xl uppercase font-black text-center mt-10">Pick your favourite.</h1>
          <section className="flex justify-between flex-wrap mt-20">
            <VoteCard>Apple</VoteCard>
            <VoteCard>Ball</VoteCard>
            <VoteCard>Cat</VoteCard>
            <VoteCard>Cat</VoteCard>
          </section>
        </div>
      </main>
    </div>
  );
};

export default Home;
