/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VotingDapp } from "./VotingDapp";

export { VotingDapp__factory } from "./factories/VotingDapp__factory";
