/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface VotingDappInterface extends utils.Interface {
  functions: {
    "Candidates(uint256)": FunctionFragment;
    "becomeCandidate(string,uint256)": FunctionFragment;
    "currentStatus(uint256)": FunctionFragment;
    "electionStarted()": FunctionFragment;
    "endElection()": FunctionFragment;
    "getCandidate(uint256)": FunctionFragment;
    "getResult()": FunctionFragment;
    "manager()": FunctionFragment;
    "startElection()": FunctionFragment;
    "totalCandidates()": FunctionFragment;
    "totalVotes()": FunctionFragment;
    "vote(uint256)": FunctionFragment;
    "winner()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "Candidates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "becomeCandidate",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "electionStarted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "endElection",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCandidate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getResult", values?: undefined): string;
  encodeFunctionData(functionFragment: "manager", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "startElection",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalCandidates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVotes",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "vote", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "winner", values?: undefined): string;

  decodeFunctionResult(functionFragment: "Candidates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "becomeCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "electionStarted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getResult", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "manager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCandidates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalVotes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "winner", data: BytesLike): Result;

  events: {};
}

export interface VotingDapp extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VotingDappInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    Candidates(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        candidateName: string;
        candidateAge: BigNumber;
        totalVotes: BigNumber;
      }
    >;

    becomeCandidate(
      _name: string,
      _age: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    currentStatus(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & { _candidateName: string; _totalVotes: BigNumber }
    >;

    electionStarted(overrides?: CallOverrides): Promise<[boolean]>;

    endElection(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getCandidate(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { _name: string; _age: BigNumber }>;

    getResult(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    manager(overrides?: CallOverrides): Promise<[string]>;

    startElection(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totalCandidates(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalVotes(overrides?: CallOverrides): Promise<[BigNumber]>;

    vote(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    winner(overrides?: CallOverrides): Promise<[string]>;
  };

  Candidates(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      candidateName: string;
      candidateAge: BigNumber;
      totalVotes: BigNumber;
    }
  >;

  becomeCandidate(
    _name: string,
    _age: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  currentStatus(
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber] & { _candidateName: string; _totalVotes: BigNumber }
  >;

  electionStarted(overrides?: CallOverrides): Promise<boolean>;

  endElection(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getCandidate(
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { _name: string; _age: BigNumber }>;

  getResult(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  manager(overrides?: CallOverrides): Promise<string>;

  startElection(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totalCandidates(overrides?: CallOverrides): Promise<BigNumber>;

  totalVotes(overrides?: CallOverrides): Promise<BigNumber>;

  vote(
    _index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  winner(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    Candidates(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        candidateName: string;
        candidateAge: BigNumber;
        totalVotes: BigNumber;
      }
    >;

    becomeCandidate(
      _name: string,
      _age: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    currentStatus(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & { _candidateName: string; _totalVotes: BigNumber }
    >;

    electionStarted(overrides?: CallOverrides): Promise<boolean>;

    endElection(overrides?: CallOverrides): Promise<void>;

    getCandidate(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { _name: string; _age: BigNumber }>;

    getResult(
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & { _candidateName: string; _totalVotes: BigNumber }
    >;

    manager(overrides?: CallOverrides): Promise<string>;

    startElection(overrides?: CallOverrides): Promise<void>;

    totalCandidates(overrides?: CallOverrides): Promise<BigNumber>;

    totalVotes(overrides?: CallOverrides): Promise<BigNumber>;

    vote(_index: BigNumberish, overrides?: CallOverrides): Promise<void>;

    winner(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    Candidates(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    becomeCandidate(
      _name: string,
      _age: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    currentStatus(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    electionStarted(overrides?: CallOverrides): Promise<BigNumber>;

    endElection(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getCandidate(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getResult(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    manager(overrides?: CallOverrides): Promise<BigNumber>;

    startElection(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totalCandidates(overrides?: CallOverrides): Promise<BigNumber>;

    totalVotes(overrides?: CallOverrides): Promise<BigNumber>;

    vote(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    winner(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    Candidates(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    becomeCandidate(
      _name: string,
      _age: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    currentStatus(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    electionStarted(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    endElection(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getCandidate(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getResult(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    manager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    startElection(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totalCandidates(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalVotes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    vote(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    winner(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
